### PR TITLE
feat: istio gateway configurable secret name and certmanager usage

### PR DESCRIPTION
**Pull request by dkhachyan**
Added ability to configure certManager usage and tls secret name for istio gateway. If I missed something please let me know and I`ll fix it.

### CODE REVIEW

**Comment by thesuperzapper** [comment]
@dkhachyan can you clarify the use-case you are trying to support here?

**Comment by dkhachyan** [comment]
In case when it`s not possible to keep CA certificate and key inside kubernetes as a result it will not be possible to create cert-manager issuer. These changes make it possible to disable cert-manager usage for istio gateway certificate generation so we can use existing secret with certificate.

May be it`s better to add `useCertManager` variable and disable certificate generation regardless of whether certManager enabled  or not globally?

**Comment by dkhachyan** [comment]
@thesuperzapper what do you think about giving ability to use existing secret with certificate for istio gateway?

**Comment by thesuperzapper** [comment]
@dkhachyan sorry for the late reply, but we can't allow users to directly set a custom certificate (at least in this way).

However, you can follow [__this guide__](https://www.deploykf.org/guides/platform/deploykf-gateway/#use-a-custom-certificate) to create an Ingress that uses a custom TLS secret, which will have the same effect (from a user perspective) without impacting the certificate the deployKF components see when talking to each other. 

The main issue is that everything breaks if that certificate is not valid or expires, which is very likely to happen with user-provided secrets that are not automatically being refreshed by cert-manager.

**Pull request closed without merging**
